export function generateAutopilotFormula(input: {
  formulaCode: string;
  revision: string;
  productType: string;
  claim: string;
  requestText: string;
}) {
  const text = `${input.requestText} ${input.claim}`.toLowerCase();
  const isSerum = input.productType.toLowerCase().includes("serum");
  const lines = isSerum ? [
    ["A","RM-00001","정제수","Water","정제수",77.0,"Solvent"],
    ["A","RM-00002","글리세린","Glycerin","글리세린",5.0,"Humectant"],
    ["A","RM-00003","부틸렌글라이콜","Butylene Glycol","부틸렌글라이콜",7.0,"Humectant"],
    ["A","RM-00024","나이아신아마이드","Niacinamide","나이아신아마이드",5.0,"Skin Conditioning"],
    ["A","RM-00022","판테놀","Panthenol","판테놀",3.0,"Skin Conditioning"],
    ["A","RM-00019","소듐하이알루로네이트","Sodium Hyaluronate","소듐하이알루로네이트",0.2,"Humectant"],
    ["A","RM-00098","잔탄검","Xanthan Gum","잔탄검",0.3,"Viscosity Increasing"],
    ["C","RM-00163","페녹시에탄올","Phenoxyethanol","페녹시에탄올",0.8,"Preservative"],
    ["C","RM-00164","에틸헥실글리세린","Ethylhexylglycerin","에틸헥실글리세린",0.7,"Preservative Booster"],
    ["C","RM-00112","시트릭애씨드","Citric Acid","시트릭애씨드",1.0,"pH Adjuster"],
  ] : [
    ["A","RM-00001","정제수","Water","정제수",68.5,"Solvent"],
    ["A","RM-00002","글리세린","Glycerin","글리세린",5.0,"Humectant"],
    ["A","RM-00003","부틸렌글라이콜","Butylene Glycol","부틸렌글라이콜",6.0,"Humectant"],
    ["B","RM-00041","스쿠알란","Squalane","스쿠알란",8.0,"Emollient"],
    ["B","RM-00078","세테아릴알코올","Cetearyl Alcohol","세테아릴알코올",3.0,"Emulsion Stabilizer"],
    ["B","RM-00081","글리세릴스테아레이트","Glyceryl Stearate","글리세릴스테아레이트",2.5,"Emulsifier"],
    ["C","RM-00022","판테놀","Panthenol","판테놀",2.0,"Skin Conditioning"],
    ["C","RM-00036","세라마이드엔피","Ceramide NP","세라마이드엔피",0.5,"Skin Conditioning"],
    ["A","RM-00009","카보머","Carbomer","카보머",0.3,"Viscosity Increasing"],
    ["C","RM-00163","페녹시에탄올","Phenoxyethanol","페녹시에탄올",0.8,"Preservative"],
    ["C","RM-00164","에틸헥실글리세린","Ethylhexylglycerin","에틸헥실글리세린",0.7,"Preservative Booster"],
    ["C","RM-00112","시트릭애씨드","Citric Acid","시트릭애씨드",2.7,"pH Adjuster"],
  ];

  let mapped = lines.map((x, idx) => ({
    formula_code: input.formulaCode,
    revision: input.revision,
    line_no: idx + 1,
    phase: x[0],
    raw_code: x[1],
    raw_name: x[2],
    inci_en: x[3],
    inci_kr: x[4],
    percentage: x[5],
    function_en: x[6],
    note: "Generated by AI Autopilot",
  }));

  if (text.includes("저가") || text.includes("cost") || text.includes("원가")) {
    mapped = mapped.map((line) => line.inci_en === "Squalane" ? { ...line, percentage: 5, note: "Cost optimized by AI Autopilot" } : line);
    const total = mapped.reduce((sum, line) => sum + Number(line.percentage), 0);
    mapped[0].percentage = Number((Number(mapped[0].percentage) + (100 - total)).toFixed(4));
  }

  return mapped;
}
