// EU CosIng(Cosmetic Ingredient Database)의 Function 분류 참고 목록.
// 공식 DB(ec.europa.eu/growth/tools-databases/cosing)에서 실제 사용되는 대표 카테고리를 정리한 것으로,
// 전체 목록이 수시로 갱신될 수 있어 목록에 없는 값은 직접 입력도 가능하게 함(datalist 방식).
// 원료관리(RawMaterialManager)와 전성분관리(IngredientDictionaryManager)가 이 목록을 공유한다.
export const COSING_FUNCTIONS = [
  "ABRASIVE", "ANTICAKING", "ANTICORROSIVE", "ANTIDANDRUFF", "ANTIFOAMING", "ANTIMICROBIAL",
  "ANTIOXIDANT", "ANTIPERSPIRANT", "ANTIPLAQUE", "ANTISEBORRHOEIC", "ANTISTATIC", "ASTRINGENT",
  "BINDING", "BLEACHING", "BUFFERING", "BULKING", "CHELATING", "CLEANSING", "DENATURANT",
  "DEODORANT", "DEPILATORY", "EMOLLIENT", "EMULSIFYING", "EMULSION STABILISING", "EXFOLIANT",
  "FILM FORMING", "FLAVOURING", "FOAM BOOSTING", "FOAMING", "FRAGRANCE", "GEL FORMING",
  "HAIR CONDITIONING", "HAIR DYEING", "HAIR FIXING", "HUMECTANT", "HYDROTROPE", "KERATOLYTIC",
  "LIGHT STABILIZER", "MASKING", "NAIL CONDITIONING", "OPACIFYING", "ORAL CARE", "OXIDISING",
  "PERFUMING", "PLASTICISER", "PRESERVATIVE", "PROPELLANT", "REDUCING", "REFATTING", "REFRESHING",
  "SKIN CONDITIONING", "SKIN CONDITIONING - EMOLLIENT", "SKIN CONDITIONING - HUMECTANT",
  "SKIN CONDITIONING - MISCELLANEOUS", "SKIN CONDITIONING - OCCLUSIVE", "SKIN PROTECTING",
  "SMOOTHING", "SOLVENT", "SOOTHING", "STABILISING", "SUNSCREEN AGENT", "SURFACTANT",
  "SURFACTANT - CLEANSING", "SURFACTANT - EMULSIFYING", "SURFACTANT - FOAM BOOSTING",
  "SURFACTANT - FOAMING", "SURFACTANT - HYDROTROPE", "SURFACTANT - SOLUBILIZING", "TONIC",
  "UV ABSORBER", "UV FILTER", "VISCOSITY CONTROLLING",
] as const;
