"use client";

import { supabaseProductionFinal } from "@/lib/supabaseProductionFinalClient";
export type DocKind = "FORMULA_SHEET_PDF" | "INCI_LIST" | "COMPLEX_COMPONENT_TABLE" | "SINGLE_COMPONENT_TABLE";

export async function fetchDocumentFormulas(keyword = "") {
  let q = supabaseProductionFinal.from("plm_formulas").select("*").eq("is_active", true).order("updated_at", { ascending: false }).limit(100);
  if (keyword.trim()) { const k = keyword.trim(); q = q.or(`formula_code.ilike.%${k}%,formula_name.ilike.%${k}%,customer.ilike.%${k}%,product_type.ilike.%${k}%`); }
  const { data, error } = await q; if (error) throw error; return data || [];
}
export async function fetchFormulaLinesForPdf(formulaCode: string, revision: string) {
  const { data, error } = await supabaseProductionFinal.from("plm_formula_lines").select("*").eq("formula_code", formulaCode).eq("revision", revision).order("line_no", { ascending: true });
  if (error) throw error; return data || [];
}
export async function fetchPdfDocuments() {
  const { data, error } = await supabaseProductionFinal.from("plm_documents").select("*").in("document_type", ["FORMULA_SHEET_PDF","INCI_LIST","COMPLEX_COMPONENT_TABLE","SINGLE_COMPONENT_TABLE"]).order("created_at", { ascending: false }).limit(150);
  if (error) throw error; return data || [];
}
function e(v:any){return String(v??"").replace(/[&<>"']/g,(m)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]||m));}
function baseHtml(title:string, body:string){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"/><title>${e(title)}</title><style>body{margin:0;background:#f1f5f9;color:#0f172a;font-family:Arial,'Noto Sans KR',sans-serif}.page{width:980px;margin:24px auto;background:white;padding:42px;border:1px solid #dbe3ef}.header{display:flex;justify-content:space-between;border-bottom:4px solid #0f172a;padding-bottom:18px;margin-bottom:26px}h1{font-size:28px;margin:0}.sub{color:#64748b;font-size:13px;line-height:1.6}h2{font-size:18px;margin:28px 0 10px}table{width:100%;border-collapse:collapse}th{background:#0f172a;color:white}th,td{border:1px solid #cbd5e1;padding:9px;font-size:12px}.no-print{margin-top:24px;padding:12px 18px;border:0;border-radius:10px;background:#2563eb;color:white;font-weight:800}@media print{body{background:white}.page{width:auto;margin:0;border:0}.no-print{display:none}}</style></head><body><div class="page"><div class="header"><div><h1>${e(title)}</h1><div class="sub">Cosmetic PLM Enterprise Document</div></div><div class="sub">생성일: ${e(new Date().toLocaleString("ko-KR"))}</div></div>${body}<button class="no-print" onclick="window.print()">PDF로 저장/인쇄</button></div></body></html>`;}
export function buildFormulaSheetHtml(f:any, lines:any[]){const total=Number(lines.reduce((s,x)=>s+Number(x.percentage||0),0).toFixed(4));const rows=lines.map(x=>`<tr><td>${e(x.line_no)}</td><td>${e(x.phase)}</td><td>${e(x.raw_code)}</td><td>${e(x.raw_name)}</td><td>${e(x.inci_kr||x.inci_en||"")}</td><td style="text-align:right">${e(x.percentage)}%</td><td>${e(x.function_kr||x.function_en||"")}</td></tr>`).join("");return baseHtml("Formula Sheet",`<h2>처방 기본정보</h2><table><tr><th>항목</th><th>내용</th></tr><tr><td>처방코드</td><td>${e(f.formula_code)}</td></tr><tr><td>Revision</td><td>${e(f.revision)}</td></tr><tr><td>처방명</td><td>${e(f.formula_name)}</td></tr><tr><td>총합</td><td>${total}%</td></tr></table><h2>BOM</h2><table><thead><tr><th>No</th><th>Phase</th><th>원료코드</th><th>원료명</th><th>INCI</th><th>함량</th><th>기능</th></tr></thead><tbody>${rows||`<tr><td colspan="7">BOM 없음</td></tr>`}</tbody></table>`);}
export function buildInciListHtml(f:any, lines:any[]){const rows=lines.slice().sort((a,b)=>Number(b.percentage||0)-Number(a.percentage||0)).map((x,i)=>`<tr><td>${i+1}</td><td>${e(x.inci_kr||x.inci_en||x.raw_name)}</td><td>${e(x.raw_name)}</td><td style="text-align:right">${e(x.percentage)}%</td><td>${e(x.function_kr||x.function_en||"")}</td></tr>`).join("");return baseHtml("전성분표",`<h2>${e(f.formula_name)} / ${e(f.formula_code)}-${e(f.revision)}</h2><table><thead><tr><th>순서</th><th>전성분명</th><th>원료명</th><th>처방함량</th><th>기능</th></tr></thead><tbody>${rows||`<tr><td colspan="5">데이터 없음</td></tr>`}</tbody></table>`);}
export function buildComplexComponentTableHtml(f:any, lines:any[]){const rows=lines.filter(x=>String(x.inci_kr||x.inci_en||"").includes(",")).map((x,i)=>`<tr><td>${i+1}</td><td>${e(x.raw_code)}</td><td>${e(x.raw_name)}</td><td>${e(x.inci_kr||x.inci_en)}</td><td style="text-align:right">${e(x.percentage)}%</td></tr>`).join("");return baseHtml("복합성분표",`<h2>${e(f.formula_name)}</h2><table><thead><tr><th>순서</th><th>원료코드</th><th>원료명</th><th>구성 INCI</th><th>처방함량</th></tr></thead><tbody>${rows||`<tr><td colspan="5">복합성분 원료가 없습니다.</td></tr>`}</tbody></table>`);}
export function buildSingleComponentTableHtml(f:any, lines:any[]){const rows=lines.filter(x=>!String(x.inci_kr||x.inci_en||"").includes(",")).map((x,i)=>`<tr><td>${i+1}</td><td>${e(x.raw_code)}</td><td>${e(x.raw_name)}</td><td>${e(x.inci_kr||x.inci_en||"")}</td><td style="text-align:right">${e(x.percentage)}%</td><td>${e(x.function_kr||x.function_en||"")}</td></tr>`).join("");return baseHtml("단일성분표",`<h2>${e(f.formula_name)}</h2><table><thead><tr><th>순서</th><th>원료코드</th><th>원료명</th><th>INCI</th><th>처방함량</th><th>기능</th></tr></thead><tbody>${rows||`<tr><td colspan="6">단일성분 원료가 없습니다.</td></tr>`}</tbody></table>`);}
export async function createFormulaDocument(formula:any, kind:DocKind){const lines=await fetchFormulaLinesForPdf(formula.formula_code, formula.revision);const builders:any={FORMULA_SHEET_PDF:buildFormulaSheetHtml,INCI_LIST:buildInciListHtml,COMPLEX_COMPONENT_TABLE:buildComplexComponentTableHtml,SINGLE_COMPONENT_TABLE:buildSingleComponentTableHtml};const names:any={FORMULA_SHEET_PDF:"Formula Sheet",INCI_LIST:"전성분표",COMPLEX_COMPONENT_TABLE:"복합성분표",SINGLE_COMPONENT_TABLE:"단일성분표"};const html=builders[kind](formula,lines);const documentCode=`${kind}-${formula.formula_code}-${formula.revision}-${Date.now().toString().slice(-6)}`;const {data,error}=await supabaseProductionFinal.from("plm_documents").insert({document_code:documentCode,formula_code:formula.formula_code,revision:formula.revision,document_type:kind,title:`${formula.formula_name} ${names[kind]}`,status:"CREATED",payload_json:{formula,lines},html_content:html,created_by:"Sprint 2-3"}).select("*").single();if(error)throw error;return data;}
export const createFormulaSheetDocument=(formula:any)=>createFormulaDocument(formula,"FORMULA_SHEET_PDF");
export function downloadHtmlDocument(doc:any){const blob=new Blob([doc.html_content||""],{type:"text/html;charset=utf-8"});const url=URL.createObjectURL(blob);const a=window.document.createElement("a");a.href=url;a.download=`${doc.document_code||"plm-document"}.html`;a.click();URL.revokeObjectURL(url);}
export function openPrintDocument(doc:any){const win=window.open("","_blank");if(!win)throw new Error("팝업이 차단되었습니다.");win.document.open();win.document.write(doc.html_content||"");win.document.close();}
